### ISSUE TITLE
New plots on the user interface?

### ISSUE THREAD

**Issue by ChristopherRabotin** [assaydepot/dracula-covid19#16]
Hi there,

First of all, great work, and thanks for making this open source.

Secondly, I was wondering how one could contribute new plots to the user interface. Specifically, what would be of interest (in my opinion), is showing a log-linear plot of cases per country, a percentage of infected population (raw numbers aren't an excellent comparison point), and a linear regression tool per country to calculate the doubling rate of the number of confirmed cases. (Some of this is available on https://offloop.net/covid19/?default=US ).

I'd be happy to help implement that, but I haven't seen any of the plotting functions in this repo. Is it configured on scientist.com?

Thanks

**Comment by xrl** [comment]
Hi @ChristopherRabotin, sorry for the late reply. The dashboard is made with tableau desktop (a piece of non-free, license software) and then published to tableau's public hosting server. @cfrench575 is it possible to include a copy of the dashboard without the AWS credentials embedded? Maybe even a one-time snapshot of the tableau file?

**Comment by cfrench575** [comment]
Hi @ChristopherRabotin we can include a copy of the .twb file. Unfortunately Tableau is not free however I think you could use a combination of the tableau public server and the 2-week free trial of the desktop version to take a look at it. I also want to note that the "continent" column is created using case when statement in SQL so that particular variable won't work with this data
